### ISSUE TITLE
Alter market to behave realistically

### ISSUE THREAD

**Issue by evangipson** [evangipson/microstocks#15]
After speaking with my econ major friend Kyle, he let me know a few things after playing the game.
- **_Stick with the slow-growth economy**_: so that if you did buy one of everything, you'd slowly succeed. The market is too volatile/stagnant/random as it is. Might as well sit on your portfolio and hope for a huge increase - there is no strategy involved.
- **_Make different stocks on different dice rolls**_: make some stable, generally (but not always) trending up by $1-$2 dollars. make some volatile(upwards) v(stag) and  v(down). make some stable but failing. Currently every stock is treated the same, when really they'd be from different risk companies.
  - _Note: I really like this idea, this will probably be the first thing I implement_
- **_Bankruptcy**_: when a stock gets to like value <$1, the stock should be canceled, all of the stock you have in that company nulled, and a new company replaces it.
  - _Note: Totally agree, that keeps it fresh too!_

**Comment by robertpateii** [comment]
Yeah i like these ideas too

**Comment by evangipson** [comment]
Created a new issue to turn stocks into space resources, which will balance out other stuff in the market, but I will be doing all the things noted in this issue. Just over here https://github.com/evangipson/microstocks/issues/17 instead.
